name: Build Validation

on:
  push:
    paths:
      - "infra_technical/ci-cd/**"
    branches:
      - main
  pull_request:
    paths:
      - "infra_technical/ci-cd/**"

jobs:
  build-validation:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # 4. Build Python package
      - name: Build package
        run: |
          python -m build
          ls -lh dist/

      # 5. Validate artifacts with Twine
      - name: Validate artifacts
        run: |
          twine check dist/*

      # 6. Upload build artifacts for audit
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: finsig-build-artifacts
          path: dist/*

      # 7. Verify installability
      - name: Verify installability
        run: |
          python -m venv venv_test
          source venv_test/bin/activate
          pip install dist/*.whl
          python -c "import finsig; print('FINSIG package import OK')"
