name: FINSIG CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:   # Permet de lancer manuellement

jobs:
  # 1️⃣ Tests unitaires + couverture
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov=core/architecture --cov-report=term-missing

  # 2️⃣ Lint & sécurité
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Run flake8
        run: |
          flake8 core/architecture infra_technical --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 core/architecture infra_technical --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run bandit
        run: bandit -r core/architecture -r infra_technical -ll

  # 3️⃣ Build & packaging
  build:
    runs-on: ubuntu-latest
    needs: [tests, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools twine

      - name: Build package
        run: python -m build

      - name: Verify installation
        run: |
          pip install dist/*.whl
          python -c "import core.architecture; print('✅ Package import successful')"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: finsig-build
          path: dist/

  # 4️⃣ Docker build & push
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/finsig:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/finsig:latest

  # 5️⃣ Déploiement staging
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}/finsig:latest

      - name: Deploy with Docker Compose
        run: docker-compose -f infra_technical/ci-cd/workflows/docker-compose.yml up -d

      - name: Verify deployment
        run: docker ps