name: Docker Build & Push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Connexion au registre GitHub (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Construction de l’image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/finsig:latest .

      # 5️⃣ Push de l’image vers GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/finsig:latest