name: Lint & Security Checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Installation des dépendances
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      # 4️⃣ Vérification du style avec flake8
      - name: Run flake8
        run: |
          flake8 core/architecture infra_technical --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 core/architecture infra_technical --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      # 5️⃣ Vérification de sécurité avec bandit
      - name: Run bandit
        run: |
          bandit -r core/architecture -r infra_technical -ll
